server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
  shutdown_timeout: 10s
db:
  host: "localhost" #"postgres-service"
  port: 5433
  username: "postgres"
  name: "comments_tree"
  password: "postgres"